[tool.poetry]
name = "langgaph-course"
version = "0.1.0"
description = ""
authors = ["Eden Marco <emarco177@gmail.com>"]
readme = "README.md"
packages = [{ include = "graph" }]

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.12.3"
chromadb = "^0.5.0"
python-dotenv = "^1.0.1"
black = "^24.4.2"
isort = "^5.13.2"
pytest = "^8.2.0"
tiktoken = "^0.7.0"
faiss-cpu = "^1.8.0.post1"
langchainhub = "^0.1.20"
langgraph-checkpoint-sqlite = "^1.0.0"
langchain-chroma = "^0.1.3"
langchain = "^0.3.0"
langgraph = "^0.2.22"
langgraph-cli = "^0.1.52"
tavily-python = "^0.5.0"
langchain-community = "^0.3.0"
pypdf = "^5.0.0"
langchain-openai = "^0.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
